version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis_server
    restart: always
    ports:
      - "63799:6379"

  postgres:
    image: postgres:latest
    container_name: postgres_server
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_DB: evm

    volumes:
      - "${PWD}/postgres_data:/var/lib/postgresql/data"

volumes:
  postgres_data:
